version: '3'

services:
  db:
    image: postgres:16
    container_name: pg-container
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptobot
