spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cryptobot
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        naming:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
          show_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

telegram:
  bot:
    update-timeout:
      value: 2
      unit: MINUTES
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT
